### ISSUE TITLE
[step0] talos FetchError

### ISSUE THREAD

**Issue by berezovskyi** [hypermedia-app/kgc-hypermedia-app-tutorial#1]
Thanks for the workshop @tpluscode! I am fairly new to the Node ecosystem, having a problem during the setup:

```
❯ yarn bootstrap
yarn run v1.22.18
$ dotenv -c local -- run-s bootstrap:*
$ wsrun -msc bootstrap resources resources.dev
@creta-todos/explorer has no bootstrap script, skipping missing
@creta-todos/app has no bootstrap script, skipping missing
@creta-todos/todos
$ talos put --api $TODOS_BASE --endpoint $SPARQL_ENDPOINT --user $SPARQL_USER --password $SPARQL_PASSWORD resources resources.dev
 | 2022-05-02T17:01:56.805Z talos FetchError: request to http://db.creta-todos.lndo.site/repositories/creta-todos?infer=true&query=ASK%20%0AFROM%20%3Chttps%3A%2F%2Fcreta-todos.lndo.site%2Ftodos%2Fapi%2Fauthorization%2Fsystem-controls-all%3E%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D%0A failed, reason: connect ECONNREFUSED 127.0.0.1:80
 |     at ClientRequest.<anonymous> (/Users/ezandbe/git/tmp/kgc-hypermedia-app-tutorial/node_modules/@zazuko/node-fetch/lib/index.js:1483:11)
 |     at ClientRequest.emit (node:events:527:28)
 |     at Socket.socketErrorListener (node:_http_client:454:9)
 |     at Socket.emit (node:events:527:28)
 |     at emitErrorNT (node:internal/streams/destroy:157:8)
 |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
 |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn bootstrap resources resources.dev` failed with exit code 1
@creta-todos/users
$ talos put --api $USERS_BASE --endpoint $SPARQL_ENDPOINT --user $SPARQL_USER --password $SPARQL_PASSWORD resources resources.dev
 | 2022-05-02T17:01:57.593Z talos FetchError: request to http://db.creta-todos.lndo.site/repositories/creta-todos?infer=true&query=ASK%20%0AFROM%20%3Chttps%3A%2F%2Fcreta-todos.lndo.site%2Fusers%2Fapi%2Fauthorization%2Fsystem-controls-all%3E%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D%0A failed, reason: connect ECONNREFUSED 127.0.0.1:80
 |     at ClientRequest.<anonymous> (/Users/ezandbe/git/tmp/kgc-hypermedia-app-tutorial/node_modules/@zazuko/node-fetch/lib/index.js:1483:11)
 |     at ClientRequest.emit (node:events:527:28)
 |     at Socket.socketErrorListener (node:_http_client:454:9)
 |     at Socket.emit (node:events:527:28)
 |     at emitErrorNT (node:internal/streams/destroy:157:8)
 |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
 |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn bootstrap resources resources.dev` failed with exit code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "bootstrap:dev" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Do I need to run some lando command first? The README for step0 did not mention it and I don't see any command in `package.json` that runs lando.

This is what I have (macOS + ZSH):

```
❯ node -v
v16.15.0

❯ npm -v
8.5.5

❯ yarn -v
1.22.18

❯ lando version
v3.6.5
```

**Comment by tpluscode** [comment]
Good catch, @berezovskyi.

You are right, of course. You would need to call `lando start` which runs the local environment (database, API, others)

**Comment by tpluscode** [comment]
I updated `step-0` now

**Comment by berezovskyi** [comment]
Thanks, all works now!
